---
- name: Install Docker and Apache
  hosts: ec2
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install Docker repository
      apt_repository:
        repo: |
          deb [arch=amd64] https://download.docker.com/linux/ubuntu
          {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: true